#!/bin/bash
# Nearsoft, Inc.
# Nearsoft Labs

case $OSTYPE in
        darwin*)
                os="mac"
        ;;
        linux-gnu)
                os="linux"
        ;;
esac

function installGems() {
    echo "Installing gems $gems" 
    sudo gem install $1
}

function toLowerCase() {
    echo $1 | tr "[:upper:]" "[:lower:]"
}

# Checks if a command exits: Returns 1 if the command exits
function isInstalled(){
    if type $1 > /dev/null 2>&1; then
        echo "1"
    else echo "0"
    fi
}

# Function for required packages installation
function installPackage(){
    check=$(isInstalled $1);
    if [ $check == 0 ]; then
            echo -e "Installing $1." 
            $pack $1
    fi
}

# Execute getopt on the arguments passed to this program, identified by the special character $@
PARSED_OPTIONS=$(getopt -n "$0"  -o hr:R:nsg: --long "help,ruby:,rails:,no-gems,vim-plugins,sample,gem:"  -- "$@")
 
#Bad arguments, something has gone wrong with the getopt command.
if [ $? -ne 0 ];
then
    exit 1
fi
 
# A little magic, necessary when using getopt.
eval set -- "$PARSED_OPTIONS"
 
# Initialize some variables with their defaults.
install_sample=false
ruby_v=1.9.3 # default ruby version

# Now goes through all the options with a case and using shift to analyse 1 argument at a time.
# $1 identifies the first argument, and when we use shift we discard the first argument, so $2 becomes $1 and goes again through the case.
while true;
do
    case "$1" in
        -h|--help)
            echo ""
            echo "#############"
            echo "## ruby2go ##"
            echo "#############"
            echo ""
            echo "Easily set up your ruby dev environment on GNU/Linux and Mac."
            echo ""
            echo "Usage: ./ruby2go [options [argument]...]"
            echo "i.e.:  ./ruby2go --ruby 1.9.3 --gem devise --gem pg"
            echo ""
            echo "Options:"
            echo " -g, --gem GEM          Installs the specified gem at the end of the script"
            echo " -h, --help             Show this help text"
            echo " -n, --no-gems          Do not install any gem (nor rails)"
            echo " -R, --rails VERSION    Specify what version of Rails will be installed"
            echo " -r, --ruby VERSION     Specify what version of ruby will be installed"
            echo " -s, --sample           Download the sample app when installation is complete"     

            exit 1
            shift;; 

        -r|--ruby)
            # We need to take the option of the argument "ruby"
            if [ -n "$2" ];
            then
                ruby_v=$2
                # echo "Using Ruby $2"
            fi
            shift 2;;

        -l|--rails)
            if [ -n "$2" ];
            then
                rails_v=$2
                # echo "Using Rails $2"
            fi
            shift 2;;

        -n|--no-gems)
                gems=false
            shift;;
        -s|--sample)
                install_sample=true
            shift;;
        -g|--gem)
            if [ -n "$2" ]; then
                gems="$gems $2"
            fi
            shift 2;;
        --)
            shift
            break;;
    esac
done

# Make sure this script is not being executed as root
if [ "$(id -u)" == "0" ]; then
   echo "Don't run this script as root." 1>&2
   exit 1
fi

echo -e "\e[1;37mWelcome to Ruby2Go: The best way to install Ruby.\e[0m"    #Print logo

if [ $os == "linux" ]; then
    # Detect the proper package manager
    pkm_apt_binary="$(     builtin command -v apt-get )"
    pkm_emerge_binary="$(  builtin command -v emerge  )"
    pkm_pacman_binary="$(  builtin command -v pacman  )"
    pkm_yum_binary="$(     builtin command -v yum     )"
    pkm_zypper_binary="$(  builtin command -v zypper  )"
    pkm_pkg_add_binary="$( builtin command -v pkg_add )"

    # Checks if evaluated package manager is installed
    if [[ -n "$pkm_apt_binary" ]]; then
        pack="sudo apt-get install -y"
        rvm_dependencies="build-essential openssl libreadline6 libreadline6-dev curl git-core zlib1g zlib1g-dev libssl-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt-dev autoconf libc6-dev ncurses-dev automake libtool bison subversion pkg-config"
    elif [[ -n "$pkm_emerge_binary" ]]; then
        pack="sudo emerge"
        rvm_dependencies="libiconv readline zlib openssl curl git libyaml sqlite libxslt libtool gcc autoconf automake bison m4"
    elif [[ -n "$pkm_pacman_binary" ]]; then
        pack="sudo pacman -Sy --noconfirm"
        rvm_dependencies="gcc patch curl zlib readline libxml2 libxslt git autoconf automake diffutils make libtool bison subversion"
    elif [[ -n "$pkm_yum_binary" ]]; then
        pack="sudo yum install -y"
        rvm_dependencies="gcc-c++ patch readline readline-devel zlib zlib-devel libyaml-devel libffi-devel openssl-devel make bzip2 autoconf automake libtool bison iconv-devel"
    elif [[ -n "$pkm_zypper_binary" ]]; then
        pack="sudo zypper install -y"
        rvm_dependencies="patterns-openSUSE-devel_basis gcc-c++ bzip2 readline-devel zlib-devel libxml2-devel libxslt-devel libyaml-devel libopenssl-devel libffi45-devel libtool bison"
    elif [[ -n "$pkm_pkg_add_binary" ]]; then
        pack="sudo pkg_add"
        rvm_dependencies="gcc curl readline libxml2 libxslt git autoconf automake diffutils make libtool bison subversion"
    else
        echo "No package manager found!"
        exit 2
    fi

    # Required packages
    installPackage "curl"
    installPackage "git"
    installPackage "nodejs"

    # Install RVM with curl
    curl -L get.rvm.io | bash -s stable

    source $HOME/.rvm/scripts/rvm

    $pack $rvm_dependencies

    rvm pkg install openssl

elif [ $os == "mac" ]; then
    echo "Do you want to use Homebrew? [Y/n]"
    read use_homebrew

    if [[ $use_homebrew == "Y" || $use_homebrew == "y" || $use_homebrew == "" ]]; then
        echo "Installing Homebrew ..."
        ruby <(curl -fsS https://raw.github.com/mxcl/homebrew/go)
        brew update

        # Putting Homebrew to PATH
        echo "export PATH='/usr/local/bin:$PATH'" >> ~/.zshenv
        source ~/.zshenv

        # Installing GNU compiler collection and dependencies
        brew tap homebrew/dupes
        brew install autoconf automake apple-gcc42

        brew install libksba

        # Install RVM
        curl -L https://get.rvm.io | bash -s stable

        # Use ruby version defined
        rvm use $ruby_v
        rvm --default $ruby_v
        rvm default 
    else
        echo "Can't install Ruby on Rails without using Homebrew yet."
        echo ""
    fi
fi
 
rvm install $ruby_v --with-openssl-dir=$HOME/.rvm/usr
rvm use $ruby_v --default

rails=`toLowerCase $rails`

gems="execjs $gems"

if [[ $rails != "no" ]]; then
    gems="rails $gems"
fi

if [[ $gems != false ]]; then 
    installGems $gems
fi

if [[ $install_sample == true ]]; then
    git clone https://github.com/Nearsoft/pawnil.git
    cd pawnil

    bundle install --without production
    rake db:migrate
    cd ..
    echo "Now you can try the sample app by running \"rails s\" inside \"pawnil\" subfolder."
    echo ""
fi

echo -e "Great, you've got everything installed. Happy Coding." 
bash --login # needed for recently installed packages take effect
# TODO: Print logo